/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santaclaus;

import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author developer
 */
public class Main extends javax.swing.JFrame {

    public static int ULTIMO_RENO = 9;
    public static int CANT_ELFOS_ATENCION = 3;

    public static DefaultListModel modelListaRenos;
    public static DefaultListModel modelListaElfos;
    public static DefaultListModel modelListaSalaEspera;

    /**
     * Inicializamos los semaforos de elfos y renos en 0, para que al iniciar
     * esten a la espera. El que cambia este valor es Santa
     */
    public static Semaphore semElfos = new Semaphore(3, true);
    public static Semaphore semRenos = new Semaphore(0, true);
    public static Semaphore semSanta = new Semaphore(0, true);
    public static Semaphore mutex = new Semaphore(1);

    public int contador = 0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setInitialConfig();

    }

    private void setInitialConfig() {

        modelListaElfos = new DefaultListModel();
        modelListaRenos = new DefaultListModel();
        modelListaSalaEspera = new DefaultListModel();

        listaElfos.setModel(modelListaElfos);
        listaRenos.setModel(modelListaRenos);
        listaSalaEspera.setModel(modelListaSalaEspera);

        updateLabelElfos();
        updateLabelRenos();

        SantaClaus s = new SantaClaus();
        s.start();

    }

    public static void updateLabelElfos() {
        txtElfosStatic.setText(modelListaElfos.size() + " Elfos");
    }

    public static void updateLabelRenos() {
        txtRenosStatic.setText(modelListaRenos.size() + " Renos");
    }
    
    public static void despertarSanta(){
        imagenSanta.setIcon(new javax.swing.ImageIcon(Main.class.getResource("/santaclaus/santa_despierto.png")));
    }
    
    public static void dormirSanta(){
        imagenSanta.setIcon(new javax.swing.ImageIcon(Main.class.getResource("/santaclaus/santa_durmiendo.png")));
    }

    private void addReno() {
        try {
            mutex.acquire();
            Reno r = new Reno(modelListaRenos.size());
            r.start();
            modelListaRenos.addElement(r);
            updateLabelRenos();
            mutex.release();
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addElfo() {
        try {
            mutex.acquire();
            Elfo e = new Elfo(contador++);

            if (modelListaSalaEspera.size() < CANT_ELFOS_ATENCION) {
                modelListaSalaEspera.addElement(e);
            } else {
                modelListaElfos.addElement(e);
                updateLabelElfos();
            }

            e.start();

            mutex.release();
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaRenos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaElfos = new javax.swing.JList<>();
        btnElfo = new javax.swing.JButton();
        btnReno = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        txtRenos = new javax.swing.JLabel();
        txtElfos = new javax.swing.JLabel();
        txtElfosStatic = new javax.swing.JLabel();
        txtRenosStatic = new javax.swing.JLabel();
        imagenSanta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaSalaEspera = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listaRenos);

        jScrollPane2.setViewportView(listaElfos);

        btnElfo.setText("+ Elfo");
        btnElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElfoActionPerformed(evt);
            }
        });

        btnReno.setText("+ Reno");
        btnReno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenoActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        txtElfosStatic.setText("jLabel1");

        txtRenosStatic.setText("jLabel1");

        imagenSanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santaclaus/santa_durmiendo.png"))); // NOI18N

        jScrollPane3.setViewportView(listaSalaEspera);

        jLabel1.setText("SalaDeEspera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtElfosStatic)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnElfo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagenSanta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRenosStatic, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtElfos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRenos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtElfosStatic)
                            .addComponent(txtRenosStatic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElfo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRenos)
                    .addComponent(txtElfos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(imagenSanta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnReiniciar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenoActionPerformed
        addReno();
    }//GEN-LAST:event_btnRenoActionPerformed

    private void btnElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElfoActionPerformed
        addElfo();
    }//GEN-LAST:event_btnElfoActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        setInitialConfig();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElfo;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnReno;
    public static javax.swing.JLabel imagenSanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaElfos;
    private javax.swing.JList<String> listaRenos;
    private javax.swing.JList<String> listaSalaEspera;
    private javax.swing.JLabel txtElfos;
    private static javax.swing.JLabel txtElfosStatic;
    private javax.swing.JLabel txtRenos;
    private static javax.swing.JLabel txtRenosStatic;
    // End of variables declaration//GEN-END:variables
}
